// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// between_num
LogicalVector between_num(NumericVector x, NumericVector from, NumericVector to, bool left_closed, bool right_closed);
RcppExport SEXP _aurora_between_num(SEXP xSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP left_closedSEXP, SEXP right_closedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type left_closed(left_closedSEXP);
    Rcpp::traits::input_parameter< bool >::type right_closed(right_closedSEXP);
    rcpp_result_gen = Rcpp::wrap(between_num(x, from, to, left_closed, right_closed));
    return rcpp_result_gen;
END_RCPP
}
// binaryTree_cpp
Rcpp::IntegerVector binaryTree_cpp(int n);
RcppExport SEXP _aurora_binaryTree_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binaryTree_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// conv_DecToBin
CharacterVector conv_DecToBin(IntegerVector n);
RcppExport SEXP _aurora_conv_DecToBin(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(conv_DecToBin(n));
    return rcpp_result_gen;
END_RCPP
}
// formatDateTime
CharacterVector formatDateTime(SEXP x, std::string fmt, bool strict, std::string locale);
RcppExport SEXP _aurora_formatDateTime(SEXP xSEXP, SEXP fmtSEXP, SEXP strictSEXP, SEXP localeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< std::string >::type locale(localeSEXP);
    rcpp_result_gen = Rcpp::wrap(formatDateTime(x, fmt, strict, locale));
    return rcpp_result_gen;
END_RCPP
}
// formatNum
CharacterVector formatNum(NumericVector x, Nullable<IntegerVector> digits, Nullable<IntegerVector> ldigits, Nullable<CharacterVector> big_mark, Nullable<CharacterVector> decimal_mark, int sci_big, int sci_small);
RcppExport SEXP _aurora_formatNum(SEXP xSEXP, SEXP digitsSEXP, SEXP ldigitsSEXP, SEXP big_markSEXP, SEXP decimal_markSEXP, SEXP sci_bigSEXP, SEXP sci_smallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type ldigits(ldigitsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type big_mark(big_markSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type decimal_mark(decimal_markSEXP);
    Rcpp::traits::input_parameter< int >::type sci_big(sci_bigSEXP);
    Rcpp::traits::input_parameter< int >::type sci_small(sci_smallSEXP);
    rcpp_result_gen = Rcpp::wrap(formatNum(x, digits, ldigits, big_mark, decimal_mark, sci_big, sci_small));
    return rcpp_result_gen;
END_RCPP
}
// pSmirnov2x
double pSmirnov2x(double statistic, int nx, int ny);
RcppExport SEXP _aurora_pSmirnov2x(SEXP statisticSEXP, SEXP nxSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(pSmirnov2x(statistic, nx, ny));
    return rcpp_result_gen;
END_RCPP
}
// pKS2
NumericVector pKS2(NumericVector statistic, double tol);
RcppExport SEXP _aurora_pKS2(SEXP statisticSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pKS2(statistic, tol));
    return rcpp_result_gen;
END_RCPP
}
// pKolmogorov2x
double pKolmogorov2x(double statistic, int n);
RcppExport SEXP _aurora_pKolmogorov2x(SEXP statisticSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(pKolmogorov2x(statistic, n));
    return rcpp_result_gen;
END_RCPP
}
// roman2int_cpp
IntegerVector roman2int_cpp(CharacterVector x);
RcppExport SEXP _aurora_roman2int_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(roman2int_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aurora_between_num", (DL_FUNC) &_aurora_between_num, 5},
    {"_aurora_binaryTree_cpp", (DL_FUNC) &_aurora_binaryTree_cpp, 1},
    {"_aurora_conv_DecToBin", (DL_FUNC) &_aurora_conv_DecToBin, 1},
    {"_aurora_formatDateTime", (DL_FUNC) &_aurora_formatDateTime, 4},
    {"_aurora_formatNum", (DL_FUNC) &_aurora_formatNum, 7},
    {"_aurora_pSmirnov2x", (DL_FUNC) &_aurora_pSmirnov2x, 3},
    {"_aurora_pKS2", (DL_FUNC) &_aurora_pKS2, 2},
    {"_aurora_pKolmogorov2x", (DL_FUNC) &_aurora_pKolmogorov2x, 2},
    {"_aurora_roman2int_cpp", (DL_FUNC) &_aurora_roman2int_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_aurora(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
